### ISSUE TITLE
Add helm release and helm values

### ISSUE THREAD

**Issue by domenicbove** [zeqk/azuread-for-argocd-terraform#1]
First off, this code is a lifesaver! I copied it and after a few trial and errors with getting my URLS correct got it working. 

A cool addition would be to add the helm release and hook up all the values ie:
```
resource "helm_release" "argocd" {
  chart            = "argo-cd"
  repository       = "https://argoproj.github.io/argo-helm"
  name             = "argocd"
  version          = "5.42.1"
  namespace        = "argocd"
  create_namespace = true

  values = [
    templatefile("files/helm/argocd.yaml", {
      HOSTNAME = var.argocd_hostname
      CLIENT_ID = azuread_application.argocd.application_id
      CLIENT_SECRET = azuread_application_password.argocdsso.value
    })
  ]
}
```

Here's my values file ie `files/helm/argocd.yaml`
```
---
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

server:
  # since we terminate ssl at the LB, need to turn off ssl
  extraArgs:
  - --insecure

  ingress:
    enabled: true

    annotations:
      <ommitted>

    hosts:
    - "${HOSTNAME}"

configs:
  cm:
    admin.enabled: false
    url: ${HOSTNAME}
    oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/<hardcoded tenant id, but could probably be terraform pulled down>/v2.0
      clientID: ${CLIENT_ID}
      clientSecret: $oidc.azure.clientSecret
      requestedIDTokenClaims:
          groups:
            essential: true
      requestedScopes:
          - openid
          - profile
          - email
  secret:
    extra:
      oidc.azure.clientSecret: ${CLIENT_SECRET}
```

One finding I had was that `azuread_application_password.argocdsso.value` was already base64 encoded, dont use the base64encode function for it.
